version: '3'

services:
  web:
    build: .
    volumes:
      - ./digital-pleasures/src/:/usr/src/app/digital-pleasures/src/
      - /usr/src/app/digital-pleasures/node_modules/
    ports:
      - "3000:3000"
